import { Link } from "gatsby"
import React from "react"
import { Col, Container, Row, Button, ProgressBar } from "react-bootstrap"

import AboutmeSectionStyles from "./AboutmeSection.module.scss"
const AboutmeSection = () => {

	return (
		<Container className={AboutmeSectionStyles.aboutmeSection} fluid>
			{/* Generated by https://smooth.ie/blogs/news/svg-wavey-transitions-between-sections */}
			<svg viewBox="0 0 500 150" preserveAspectRatio="none">
				<path d="M0.00,49.98 C180.86,149.50 327.03,0.50 500.00,49.98 L500.00,150.00 L0.00,150.00 Z"></path>
			</svg>

			<Container className={AboutmeSectionStyles.whoiam} fluid>
				<Row><h4>Who I am?</h4></Row>
				<Row><Button variant="info"><Link to="/about/">About me</Link></Button></Row>
			</Container>

			<Container className={AboutmeSectionStyles.whaticando} fluid>
				<Row>
					<Col xs={12} lg={3}>
						<h4>And what can I do?</h4>
						<Button variant="info"><Link to="/skills/">My skills</Link></Button>
					</Col>

					<Col xs={12} lg={4}>
						<p>
							HTML / CSS (Sass, Less) <span>90%</span>
							<ProgressBar striped variant="info" now={90} animated />
						</p>
						<p>
							TypeScript / Angular 9 <span>60%</span>
							<ProgressBar striped variant="danger" now={60} animated />
						</p>
						<p>
							Node / Express <span>75%</span>
							<ProgressBar striped variant="success" now={75} animated />
						</p>
						<p>
							JavaScript / JQuery / React <span>95%</span>
							<ProgressBar striped variant="primary" now={95} animated />
						</p>
						<p>
							Gatsby / GraphQL <span>65%</span>
							<ProgressBar striped variant="dark" now={65} animated />
						</p>
						<p>
							MariaDB / MySQL <span>80%</span>
							<ProgressBar striped variant="warning" now={80} animated />
						</p>
						<p>
							MongoDB <span>55%</span>
							<ProgressBar striped variant="success" now={55} animated />
						</p>
					</Col>

					<Col xs={12} lg={4}>
						<p>
							PHP / Laravel / Symphony <span>30%</span>
							<ProgressBar striped variant="danger" now={30} animated />
						</p>
						<p>
							Git / Trello / Jira / Slack <span>95%</span>
							<ProgressBar striped variant="info" now={95} animated />
						</p>
						<p>
							Wordpress / Prestashop / Drupal <span>70%</span>
							<ProgressBar striped variant="warning" now={70} animated />
						</p>
						<p>
							Docker <span>75%</span>
							<ProgressBar striped variant="primary" now={75} animated />
						</p>
						<p>
							Linux services <span>65%</span>
							<ProgressBar striped variant="success" now={65} animated />
						</p>
						<p>
							Framer / Sketch / Photoshop <span>20%</span>
							<ProgressBar striped variant="info" now={20} animated />
						</p>
						<p>
							Doc writing / Communication <span>95%</span>
							<ProgressBar striped variant="dark" now={95} animated />
						</p>
					</Col>
				</Row>
			</Container>
		</Container>
	)
}

export default AboutmeSection