import { Link } from "gatsby"
import React from "react"
import { Col, Container, Row, Button, ProgressBar } from "react-bootstrap"
import { Kanban, CodeSlash } from "react-bootstrap-icons"

import SkillbarsStyles from "./Skillbars.module.scss"

const Skillbars = () => {

	return (
		<Container className={SkillbarsStyles.container} fluid>
			{/* Generated by https://smooth.ie/blogs/news/svg-wavey-transitions-between-sections */}
			<svg viewBox="0 0 500 150" preserveAspectRatio="none">
				<path d="M0.00,49.98 C180.86,149.50 327.03,0.50 500.00,49.98 L500.00,150.00 L0.00,150.00 Z"></path>
			</svg>

			<Container className={SkillbarsStyles.whoiam} fluid>
				<div>
					<h3>Web design <br/> <CodeSlash/></h3> 
				</div>
			</Container>
			
			<svg viewBox="0 0 500 150" preserveAspectRatio="none" className={SkillbarsStyles.invertedSvg}>
				<path d="M0.00,49.98 C180.86,149.50 327.03,0.50 500.00,49.98 L500.00,150.00 L0.00,150.00 Z"></path>
			</svg>

			<Container className={SkillbarsStyles.whaticando} fluid>
				<Row>
					<Col xs={12} lg={3} className={SkillbarsStyles.label}>
						<h4><Kanban/> What I can do?</h4>
						<Button variant="info"><Link to="/skills/">My skills</Link></Button>
					</Col>

					<Col xs={12} lg={4} className={SkillbarsStyles.progressBars}>
						<div>
							HTML / CSS (Sass, Less) <span>95%</span>
							<ProgressBar variant="info" now={95} />
						</div>
						<div>
							TypeScript / Angular 9 <span>80%</span>
							<ProgressBar variant="danger" now={80} />
						</div>
						<div>
							Node / Express <span>75%</span>
							<ProgressBar variant="success" now={75} />
						</div>
						<div>
							JavaScript / JQuery / React <span>95%</span>
							<ProgressBar variant="primary" now={95} />
						</div>
						<div>
							Gatsby / GraphQL <span>85%</span>
							<ProgressBar variant="dark" now={85} />
						</div>
						<div>
							MariaDB / MySQL <span>75%</span>
							<ProgressBar variant="warning" now={75} />
						</div>
						<div>
							MongoDB <span>55%</span>
							<ProgressBar variant="success" now={55} />
						</div>
					</Col>

					<Col xs={12} lg={4} className={SkillbarsStyles.progressBars}>
						<div>
							PHP / Laravel / Symphony <span>30%</span>
							<ProgressBar variant="danger" now={30} />
						</div>
						<div>
							Git / Trello / Jira / Slack <span>95%</span>
							<ProgressBar variant="info" now={95} />
						</div>
						<div>
							Wordpress / Prestashop / Drupal <span>70%</span>
							<ProgressBar variant="warning" now={70}  />
						</div>
						<div>
							Docker <span>75%</span>
							<ProgressBar variant="primary" now={75} />
						</div>
						<div>
							Linux services <span>65%</span>
							<ProgressBar variant="success" now={65} />
						</div>
						<div>
							Framer / Sketch / Photoshop <span>20%</span>
							<ProgressBar variant="danger" now={20} />
						</div>
						<div>
							Doc writing / Communication <span>95%</span>
							<ProgressBar variant="dark" now={95} />
						</div>
					</Col>
				</Row>
			</Container>
		</Container>
	)
}

export default Skillbars